String startpage = "Security fest 2019\n"
          "\n"
          "# Official badge\n"
          "## Components\n"
          "1 Nokia 5110 84x48 LCD\n"
          "1 ESP-12F module\n"
          "2 100nF capacitors\n"
          "1 10uF capacitor\n"
          "1 1kOhm resistor\n"
          "8 10kOhm resistors\n"
          "1 470Ohm resitor\n"
          "1 Push button\n"
          "2 Toggle switches\n"
          "1 3.3V LD1117V33 Voltage regulator\n"
          "1 MicroUSB connector\n"
          "\n"
          "## Flash badge\n"
          "1. Connect TX (badge) to RX (USB FTDI cable) and RX (badge) to TX (USB FTDI cable).\n"
          "2. Set UART/FLASH toggle switch to UART (GPIO0 to LOW)\n"
          "3. Power on the badge\n"
          "4. Use Arduino IDE or esptool to flash ESP-12F (ESP8266EX)\n"
          "\n"
          "## References\n"
          "1. Datasheet - https://www.elecrow.com/download/ESP-12F.pdf";

String schedule[9] = { "08:30 - Opening", "09:00 - Dude where's my car", "10:00 - WTF Did you say", "11:00 - Foobar", "12:00 - Hurry up and buy", "13:00 - LUNCH", "14:00 - MORE LUNCH", "15:00 - BEER", "Exit" };
